<template>
    <!-- Main Content -->
    <main class="flex-1 p-6">
        <h1 class="text-3xl font-bold mb-6">Dashboard Overview</h1>

        <!-- Stats Section -->
        <section class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <!-- Stat Card 1 -->
            <div class="bg-white shadow-lg rounded-lg p-6">
                <h2 class="text-lg font-semibold">Total Users</h2>
                <p class="text-4xl font-bold text-blue-600">1,234</p>
            </div>

            <!-- Stat Card 2 -->
            <div class="bg-white shadow-lg rounded-lg p-6">
                <h2 class="text-lg font-semibold">Active Sessions</h2>
                <p class="text-4xl font-bold text-green-600">567</p>
            </div>

            <!-- Stat Card 3 -->
            <div class="bg-white shadow-lg rounded-lg p-6">
                <h2 class="text-lg font-semibold">Server Load</h2>
                <p class="text-4xl font-bold text-red-600">75%</p>
            </div>
        </section>

        <!-- Recent Activity Section -->
        <section class="bg-white shadow-lg rounded-lg p-6">
            <h2 class="text-lg font-semibold mb-4">Recent Activity</h2>
            <ul class="space-y-4">
                <li class="flex justify-between">
                    <span>User John Doe logged in</span>
                    <span class="text-gray-500">2 hours ago</span>
                </li>
                <li class="flex justify-between">
                    <span>New report generated by Jane Doe</span>
                    <span class="text-gray-500">3 hours ago</span>
                </li>
                <li class="flex justify-between">
                    <span>Server updated</span>
                    <span class="text-gray-500">6 hours ago</span>
                </li>
            </ul>
        </section>
    </main>
</template>

<script setup>
definePageMeta({
    layout: 'dashboard',
});
// No special JavaScript logic required for this simple dashboard
</script>